export const FLOW_MODEL_LOADED = "FLOW_MODEL_LOADED";

export const EDITOR_CONTENT_CHANGED = "EDITOR_CONTENT_CHANGED";
export const EDITOR_HTML_CHANGED = "EDITOR_HTML_CHANGED";

export const EDITOR_SCRIPT_CHANGED = "EDITOR_SCRIPT_CHANGED";
export const EDITOR_DIALOG_CHANGED = "EDITOR_DIALOG_CHANGED";

export const EDITOR_PREVIEW_CHANGED = "EDITOR_PREVIEW_CHANGED";
export const EDITOR_FULL_TEXT_CHANGED = "EDITOR_FULL_TEXT_CHANGED";

export const EDITOR_SCRIPT_NAME_CHANGED = "EDITOR_SCRIPT_NAME_CHANGED";
export const EDITOR_SCRIPT_ARGUMENT_CHANGED = "EDITOR_SCRIPT_ARGUMENT_CHANGED";

export const EDITOR_ARGUMENT_NAME_CHANGED = "EDITOR_ARGUMENT_NAME_CHANGED";
export const EDITOR_ARGUMENT_VALUE_CHANGED = "EDITOR_ARGUMENT_VALUE_CHANGED";

export const EDITOR_ARGUMENT_ADDED = "EDITOR_ARGUMENT_ADDED";

//export const NODE_ID_SELECTED = "NODE_ID_SELECTED";
export const NODE_SELECTED = "NODE_SELECTED";

export const TITLE_SELECTED = "TITLE_SELECTED";

export const TEXT_EDITOR_TOGGLED = "TEXT_EDITOR_TOGGLED";
export const SCRIPT_EDITOR_TOGGLED = "SCRIPT_EDITOR_TOGGLED"; 

export const DRAG_COUNTER_CHANGED = "DRAG_COUNTER_CHANGED";

export const CONNECTING_TOGGLED = "CONNECTING_TOGGLED";

export const FLOW_TOOLBAR_ITEM_CHANGED = "FLOW_TOOLBAR_ITEM_CHANGED";

export const OUTGOING_CONNECTOR_ID_CHANGED = "OUTGOING_CONNECTOR_ID_CHANGED";

export const INGOING_CONNECTOR_ID_CHANGED = "INGOING_CONNECTOR_ID_CHANGED";

export const EDITOR_CHANGED = "EDITOR_CHANGED";
export const EDITOR_TOGGLED = "EDITOR_TOGGLED";

export const PREVIEW_JSON_CHANGED = "PREVIEW_JSON_CHANGED";
export const FULL_TEXT_JSON_CHANGED = "FULL_TEXT_JSON_CHANGED";

export const TITLE_CHANGED = "TITLE_CHANGED";
//export const TITLE_JSON_CHANGED = "TITLE_JSON_CHANGED";

export const NAME_CHANGED = "NAME_CHANGED";

export const SETTINGS_TOGGLED = "SETTINGS_TOGGLED";

export const AVATAR_DIRECTORY_CHANGED = "AVATAR_DIRECTORY_CHANGED";

