export const FLOW_MODEL_LOADED = "FLOW_MODEL_LOADED";

export const EDITOR_CONTENT_CHANGED = "EDITOR_CONTENT_CHANGED";
export const EDITOR_HTML_CHANGED = "EDITOR_HTML_CHANGED";

export const NODE_ID_SELECTED = "NODE_ID_SELECTED";

export const TEXT_EDITOR_TOGGLED = "TEXT_EDITOR_TOGGLED";

export const DRAG_COUNTER_CHANGED = "DRAG_COUNTER_CHANGED";

export const CONNECTING_TOGGLED = "CONNECTING_TOGGLED";

export const FLOW_TOOLBAR_ITEM_CHANGED = "FLOW_TOOLBAR_ITEM_CHANGED";




export const TESTTT = "TESTTT";